---
name: Release

on:
  push:
    branches:
      - 'release/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write # for creating the release
    name: "release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: 21

      - name: Verify release version is greater than latest on Maven Central
        run: .github/scripts/verify-version-greater-than-central.sh

      - name: Run checks
        run: ./gradlew check --stacktrace

      - name: Build and publish artifacts
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository -Pfinal=true --no-build-cache --no-configuration-cache --no-parallel
        env:
          CI: true
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}

      - name: Set environment variables
        run: |
          version=$(.github/scripts/get-version.sh)
          echo "VERSION=$version" >> $GITHUB_ENV

      - id: create-github-release
        name: Create GitHub release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v$VERSION" \
                            --target "$GITHUB_REF_NAME" \
                            --title "Version $VERSION" \
                            --generate-notes
